# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(blank=True, help_text='The sequence of the questions for a player', null=True, verbose_name='question sequence')),
                ('answer', models.IntegerField(blank=True, help_text='The answer key that was pressed during the game', null=True, verbose_name='answer given')),
                ('pickup_time', models.DateTimeField(help_text='The pick up time of the call', verbose_name='pick up time')),
                ('hangup_time', models.DateTimeField(blank=True, help_text='The hang up time of the call', null=True, verbose_name='hang up time')),
                ('correct', models.IntegerField(blank=True, help_text='This indicates if the answer is correct (1), false (0) or if there is no answer (NULL)', null=True, verbose_name='correct answer')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('number', models.IntegerField(help_text='The number of the department', primary_key=True, serialize=False, unique=True, verbose_name='department number')),
                ('name', models.CharField(help_text='The name of the department', max_length=50, verbose_name='department')),
                ('description', models.TextField(blank=True, help_text='The description of the department', null=True, verbose_name='description')),
                ('audio_file', models.FileField(blank=True, help_text="The MP3 file of the department's description", null=True, upload_to=b'departments', verbose_name='audio file')),
            ],
            options={
                'ordering': ['number'],
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='The identification code of the game', max_length=5, verbose_name='code')),
                ('team', models.CharField(help_text='The name of the team (this field is not unique!)', max_length=100, verbose_name='team')),
                ('start_time', models.DateTimeField(blank=True, help_text='The start time of the game', null=True, verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, help_text='The end time of the game', null=True, verbose_name='end time')),
                ('canceled', models.BooleanField(default=False, help_text='A game is canceled in the case of a no-show (time slot + grace period', verbose_name='canceled')),
                ('initialized', models.BooleanField(default=False, help_text='A game is initialized when the team is ready to play', verbose_name='initialized')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(help_text='The ISO 3166-1 code of the language', max_length=2, primary_key=True, serialize=False, unique=True, verbose_name='language code')),
                ('language', models.CharField(help_text='The french name of the language', max_length=100, verbose_name='language name')),
                ('flag', models.ImageField(help_text='The flag file of the language', upload_to=b'flags', verbose_name='flag file')),
                ('weight', models.IntegerField(default=1, help_text='The weight of the language in the random draw', verbose_name='language weight')),
            ],
            options={
                'ordering': ['language'],
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('number', models.IntegerField(help_text='The call number of the phone', primary_key=True, serialize=False, verbose_name='phone number')),
                ('position_x', models.FloatField(blank=True, help_text='The position on the horizontal axis', null=True, verbose_name='x position')),
                ('position_y', models.FloatField(blank=True, help_text='The position on the vertical axis', null=True, verbose_name='y position')),
                ('orientation', models.IntegerField(blank=True, default=0, help_text='The orientation of the phone in degrees', verbose_name='orientation')),
                ('usage', models.IntegerField(choices=[(10, 'Call Center Phone'), (11, 'Public Phone'), (12, 'Demo Phone'), (60, 'Test Phone')], default=60, help_text='The main use of this phone', verbose_name='phone usage')),
                ('dmx_channel', models.IntegerField(default=1, help_text='The DMX channel of the LED strip decoder', verbose_name='DMX channel')),
            ],
            options={
                'ordering': ['number'],
                'verbose_name': 'phone',
                'verbose_name_plural': 'phones',
            },
        ),
        migrations.CreateModel(
            name='Phonelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Channel is down and available'), (1, 'Channel is down, but reserved'), (2, 'Channel is off hook'), (3, 'Digits (or equivalent) have been dialed'), (4, 'Line is ringing'), (5, 'Remote end is ringing'), (6, 'Line is up'), (7, 'Line is busy')], default=0, help_text='The current status of this channel', verbose_name='status of the channel')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The timestamp of the log entry', verbose_name='timestamp')),
                ('phone', models.ForeignKey(help_text='The related phone', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='callcenter.Phone', verbose_name='phone')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, help_text='The identification number of the player', null=True, verbose_name="player's number")),
                ('name', models.CharField(blank=True, help_text='The name of the player', max_length=100, null=True, verbose_name="player's name")),
                ('score', models.IntegerField(blank=True, help_text='The final score of the player (computed at game end)', null=True, verbose_name="player's score")),
                ('game', models.ForeignKey(help_text='The game in which the player takes part', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='callcenter.Game', verbose_name='game')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('number', models.IntegerField(help_text='The number of the question', primary_key=True, serialize=False, unique=True, verbose_name='question number')),
                ('department', models.ForeignKey(help_text='The department concerned by the question (aka right answer)', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='callcenter.Department', verbose_name='department')),
            ],
            options={
                'ordering': ['number'],
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='The translated text of the question', null=True, verbose_name='translated question')),
                ('audio_file', models.FileField(help_text='The MP3 file of the question', upload_to=b'questions', verbose_name='audio file')),
                ('language', models.ForeignKey(help_text='The language of the translation', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='callcenter.Language', verbose_name='language')),
                ('question', models.ForeignKey(help_text='The translated question', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='callcenter.Question', verbose_name='question')),
            ],
            options={
                'ordering': ['question', 'language'],
                'verbose_name': 'translation',
                'verbose_name_plural': 'translations',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='phone',
            field=models.ForeignKey(help_text='The identifier of the phone used for this answer', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='callcenter.Phone', verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='answer',
            name='player',
            field=models.ForeignKey(help_text='The player who answered the question', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='callcenter.Player', verbose_name='player'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(help_text='The question/language which was answered', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='callcenter.Translation', verbose_name='question'),
        ),
    ]
