# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 10:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160824_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=10, verbose_name='Event code')),
                ('event_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of the event')),
                ('stats_date', models.DateField(verbose_name='Date of the statistics')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('stats', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
